export enum INSTALLED_BASE_ATTRIBUTES {
  COMMENT = "comment",
  CONFIGURATION_STRING = "configurationString",
  CONFIGURATION_STRING_AS_JSON = "configurationStringAsJSON",
  CREATED_FROM = "createdFrom",
  CREATED_FROM_STRONG_REF = "createdFrom_strongRef",
  CUSTOMER = "customer",
  CUSTOMER_REFERENCE = "customerReference",
  FBOM_DATE = "fbomDate",
  FBOM_REVISION = "fbomRevision",
  FINALIZED_DATE = "finalizedDate",
  HAS_BEEN_CUSTOMIZED = "hasBeenCustomized",
  HAS_BEEN_RECONFIGURED = "hasBeenReconfigured",
  ITEM_NUMBER = "itemNumber",
  NAME = "name",
  ORIGIN_PRODUCT = "originProduct",
  ORIGIN_PRODUCT_STRONG_REF = "originProduct_strongRef",
  PRODUCT_CODE = "productCode",
  PRODUCT_FAMILY_FROM_ORIGIN_PRODUCT = "productFamilyFromOriginProduct",
  PRODUCT_TYPE = "productType",
  SOURCE = "source",
  VERSION = "version",
}
